#!/usr/bin/env bash
# =============================================================================
#  OpenPortal — Domain & TLS Setup
#  Run this after setup.sh to configure a public domain with HTTPS
#  Usage: sudo bash setup-domain.sh
# =============================================================================

set -euo pipefail

BOLD='\033[1m'
DIM='\033[2m'
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

info()  { echo -e "${GREEN}  ✓${NC}  $*"; }
warn()  { echo -e "${YELLOW}  !${NC}  $*"; }
error() { echo -e "${RED}  ✗${NC}  $*" >&2; exit 1; }
step()  { echo -e "\n${BOLD}${BLUE}▸${NC}${BOLD} $*${NC}"; }
prompt() {
  local var="$1" label="$2" default="${3:-}"
  local hint=""
  [[ -n "$default" ]] && hint=" (${DIM}default: $default${NC})"
  read -rp "$(echo -e "     ${CYAN}›${NC}  ${label}${hint}: ")" value
  printf -v "$var" '%s' "${value:-$default}"
}

# ── Resolve script and repo root ──────────────────────────────────────────────
if command -v realpath &>/dev/null; then
  SCRIPT_DIR="$(cd "$(dirname "$(realpath "${BASH_SOURCE[0]}")")" && pwd)"
else
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
fi
REPO_ROOT="$SCRIPT_DIR"
ENV_FILE="$REPO_ROOT/.env"

# ── Checks ────────────────────────────────────────────────────────────────────
[[ "$EUID" -ne 0 ]] && error "Run as root: sudo bash setup-domain.sh"
command -v nginx   &>/dev/null || error "nginx is not installed. Run setup.sh --bare-metal first."
command -v certbot &>/dev/null || error "certbot is not installed. Run: apt install certbot python3-certbot-nginx"

echo -e "${BOLD}"
echo "  ╔═══════════════════════════════════════════╗"
echo "  ║       OpenPortal — Domain Setup            ║"
echo "  ╚═══════════════════════════════════════════╝"
echo -e "${NC}"

# ── Detect current config ─────────────────────────────────────────────────────
CURRENT_DOMAIN=""
CURRENT_EMAIL=""
API_PORT=8080
FRONTEND_PORT=80  # nginx serves frontend

if [[ -f "$ENV_FILE" ]]; then
  CURRENT_DOMAIN=$(grep "^PROXY_BASE_DOMAIN=" "$ENV_FILE" 2>/dev/null | cut -d= -f2 || true)
  CURRENT_EMAIL=$(grep "^ADMIN_EMAIL=" "$ENV_FILE" 2>/dev/null | cut -d= -f2 || true)
  API_PORT_ENV=$(grep "^PORT=" "$ENV_FILE" 2>/dev/null | cut -d= -f2 || true)
  [[ -n "$API_PORT_ENV" ]] && API_PORT="$API_PORT_ENV"
  info "Found existing .env: domain=$CURRENT_DOMAIN"
fi

# ── Collect inputs ────────────────────────────────────────────────────────────
step "Domain configuration"

prompt DOMAIN "Public domain name" "${CURRENT_DOMAIN:-}"
[[ -z "$DOMAIN" ]] && error "Domain cannot be empty."
[[ "$DOMAIN" == "localhost" || "$DOMAIN" == "127.0.0.1" ]] && \
  error "Use a real domain for TLS setup. For local access, no domain config is needed."

prompt EMAIL "Email for Let's Encrypt notices" "${CURRENT_EMAIL:-}"
[[ -z "$EMAIL" ]] && error "Email cannot be empty."

echo ""
echo -e "  ${DIM}This will:${NC}"
echo "    • Write an nginx virtual host for ${DOMAIN}"
echo "    • Obtain a Let's Encrypt TLS certificate"
echo "    • Update FRONTEND_URL and PROXY_BASE_DOMAIN in .env"
echo "    • Reload nginx and restart the OpenPortal service"
echo ""
read -rp "$(echo -e "     ${CYAN}?${NC}  Continue? [y/N] ")" confirm
[[ "$confirm" =~ ^[Yy]$ ]] || { echo "  Aborted."; exit 0; }

# ── Verify DNS ────────────────────────────────────────────────────────────────
step "Verifying DNS for $DOMAIN"

SERVER_IP=$(curl -sf --max-time 5 https://api.ipify.org || \
            curl -sf --max-time 5 https://ifconfig.me || \
            hostname -I | awk '{print $1}')
RESOLVED_IP=$(dig +short "$DOMAIN" 2>/dev/null | tail -1 || \
              nslookup "$DOMAIN" 2>/dev/null | awk '/^Address: /{print $2}' | tail -1 || true)

if [[ -z "$RESOLVED_IP" ]]; then
  warn "Could not resolve $DOMAIN — DNS may not be propagated yet."
  warn "Make sure an A record points $DOMAIN → $SERVER_IP"
  read -rp "$(echo -e "     ${CYAN}?${NC}  Continue anyway? [y/N] ")" dns_override
  [[ "$dns_override" =~ ^[Yy]$ ]] || exit 1
elif [[ "$RESOLVED_IP" != "$SERVER_IP" ]]; then
  warn "$DOMAIN resolves to $RESOLVED_IP but this server's IP is $SERVER_IP"
  warn "Let's Encrypt will fail if DNS doesn't point here."
  read -rp "$(echo -e "     ${CYAN}?${NC}  Continue anyway? [y/N] ")" dns_override
  [[ "$dns_override" =~ ^[Yy]$ ]] || exit 1
else
  info "$DOMAIN → $SERVER_IP (DNS OK)"
fi

# ── Write nginx config ────────────────────────────────────────────────────────
step "Writing nginx virtual host"

NGINX_CONF="/etc/nginx/sites-available/openportal"
FRONTEND_ROOT="/var/www/openportal"

cat > "$NGINX_CONF" << NGINXEOF
# OpenPortal — generated by setup-domain.sh on $(date)

# Redirect HTTP → HTTPS
server {
    listen 80;
    listen [::]:80;
    server_name ${DOMAIN};

    # Let certbot handle ACME challenges before redirect
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://\$host\$request_uri;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ${DOMAIN};

    # TLS — managed by certbot
    ssl_certificate     /etc/letsencrypt/live/${DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}/privkey.pem;
    include             /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;

    # Security headers
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
    add_header X-Frame-Options            SAMEORIGIN always;
    add_header X-Content-Type-Options     nosniff always;
    add_header Referrer-Policy            no-referrer-when-downgrade always;

    # Frontend (static files served by nginx)
    root  ${FRONTEND_ROOT};
    index index.html;

    # Service worker — no cache
    location = /sw.js {
        add_header Cache-Control "no-cache";
    }

    # Static assets — long cache
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff2|woff|ttf|webmanifest)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # API
    location /api/ {
        proxy_pass         http://127.0.0.1:${API_PORT};
        proxy_http_version 1.1;
        proxy_set_header   Host              \$host;
        proxy_set_header   X-Real-IP         \$remote_addr;
        proxy_set_header   X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto \$scheme;
        proxy_set_header   Connection        "";
        proxy_read_timeout 60s;
    }

    # Tool proxy — allow long-lived connections and large uploads
    location /proxy/ {
        proxy_pass         http://127.0.0.1:${API_PORT};
        proxy_http_version 1.1;
        proxy_set_header   Host              \$host;
        proxy_set_header   X-Real-IP         \$remote_addr;
        proxy_set_header   X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto \$scheme;
        proxy_set_header   Upgrade           \$http_upgrade;
        proxy_set_header   Connection        "upgrade";
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
        client_max_body_size 100m;
    }

    # SPA fallback
    location / {
        try_files \$uri \$uri/ /index.html;
    }

    location ~ /\. { deny all; }
}
NGINXEOF

# Ensure symlink exists
ln -sf "$NGINX_CONF" /etc/nginx/sites-enabled/openportal
rm -f /etc/nginx/sites-enabled/default

# Test config (will fail on missing cert — that's OK before certbot runs)
nginx -t 2>/dev/null || true
info "nginx virtual host written: $NGINX_CONF"

# ── Obtain TLS certificate ────────────────────────────────────────────────────
step "Obtaining TLS certificate from Let's Encrypt"

# Create webroot for ACME challenges
mkdir -p /var/www/certbot

# Temporarily serve port 80 for the ACME challenge
# Use standalone mode if nginx isn't serving yet
if nginx -t 2>/dev/null; then
  # Write a temporary HTTP-only config so certbot can complete the challenge
  cat > /etc/nginx/sites-available/openportal-tmp << TMPEOF
server {
    listen 80;
    server_name ${DOMAIN};
    root /var/www/certbot;
    location /.well-known/acme-challenge/ { root /var/www/certbot; }
    location / { return 200 'ok'; }
}
TMPEOF
  ln -sf /etc/nginx/sites-available/openportal-tmp /etc/nginx/sites-enabled/openportal-tmp
  nginx -t 2>/dev/null && systemctl reload nginx
fi

certbot certonly \
  --webroot \
  --webroot-path /var/www/certbot \
  --non-interactive \
  --agree-tos \
  --email "$EMAIL" \
  --domains "$DOMAIN" \
  || {
    # Fallback: try nginx plugin
    warn "Webroot method failed — trying nginx plugin..."
    certbot --nginx \
      --non-interactive \
      --agree-tos \
      --email "$EMAIL" \
      -d "$DOMAIN"
  }

# Remove temp config
rm -f /etc/nginx/sites-enabled/openportal-tmp
rm -f /etc/nginx/sites-available/openportal-tmp

info "TLS certificate obtained for $DOMAIN"

# ── Auto-renew ────────────────────────────────────────────────────────────────
step "Configuring certificate auto-renewal"

# Add certbot renew hook to reload nginx after renewal
mkdir -p /etc/letsencrypt/renewal-hooks/deploy
cat > /etc/letsencrypt/renewal-hooks/deploy/openportal-reload.sh << 'HOOKEOF'
#!/bin/bash
systemctl reload nginx
systemctl restart openportal 2>/dev/null || true
HOOKEOF
chmod +x /etc/letsencrypt/renewal-hooks/deploy/openportal-reload.sh

# Verify cron or systemd timer is in place
if systemctl is-active --quiet certbot.timer 2>/dev/null; then
  info "certbot.timer (systemd) is active — renewals are automatic"
elif crontab -l 2>/dev/null | grep -q certbot; then
  info "certbot cron job found — renewals are automatic"
else
  # Add cron job
  (crontab -l 2>/dev/null; echo "0 3 * * * certbot renew --quiet") | crontab -
  info "Added certbot renew cron job (daily at 03:00)"
fi

# ── Update .env ───────────────────────────────────────────────────────────────
step "Updating .env"

update_env() {
  local key="$1" value="$2" file="$3"
  if grep -q "^${key}=" "$file" 2>/dev/null; then
    sed -i "s|^${key}=.*|${key}=${value}|" "$file"
  else
    echo "${key}=${value}" >> "$file"
  fi
}

for f in "$ENV_FILE" /opt/openportal/.env; do
  [[ -f "$f" ]] || continue
  update_env "FRONTEND_URL"        "https://${DOMAIN}" "$f"
  update_env "PROXY_BASE_DOMAIN"   "$DOMAIN"           "$f"
  info "Updated: $f"
done

# ── Reload everything ─────────────────────────────────────────────────────────
step "Reloading services"

nginx -t && systemctl reload nginx
info "nginx reloaded"

if systemctl is-active --quiet openportal 2>/dev/null; then
  systemctl restart openportal
  info "openportal restarted"
fi

if command -v docker &>/dev/null && docker compose -f "$REPO_ROOT/docker-compose.yml" ps 2>/dev/null | grep -q "Up"; then
  docker compose -f "$REPO_ROOT/docker-compose.yml" restart backend
  info "Docker backend restarted"
fi

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}${GREEN}"
echo "  ╔═══════════════════════════════════════════╗"
echo "  ║       Domain setup complete!              ║"
echo "  ╚═══════════════════════════════════════════╝"
echo -e "${NC}"
echo -e "  ${BOLD}URL:${NC}       https://${DOMAIN}"
echo -e "  ${BOLD}TLS cert:${NC}  /etc/letsencrypt/live/${DOMAIN}/"
echo -e "  ${BOLD}Renews:${NC}    automatically via certbot"
echo ""
echo -e "  ${DIM}Test TLS:${NC}  curl -I https://${DOMAIN}/api/me"
echo -e "  ${DIM}Cert info:${NC} certbot certificates"
echo ""
